#!/bin/bash

# Change these entries to match your t8code library folder
BASEDIR=$HOME/execute
T8_DIR=$BASEDIR/t8code_install


# Compiler settings

CC=mpicc
CFLAGS='-Wall -pedantic --std=c99 -O0 -g'
SOURCE='../src/test.c ../src/sfccc_piece.c ../src/sfccc_searchgraph.c'

# There should be no need to change the following lines
LIB=$T8_DIR/lib
INCLUDE=$T8_DIR/include

LIBS="-lt8 -lp4est -lsc -lm -lz"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIB

# compile line
echo libraries in $LIB
echo header in $INCLUDE

echo "$CC $CFLAGS -o test $SOURCE -I$INCLUDE -L$LIB $LIBS"
$CC $CFLAGS -o test $SOURCE -I$INCLUDE -L$LIB $LIBS
